name:                risky
version:             0.1.0.0
github:              "megis7/risky"
license:             BSD3
author:              "Michalis Megisoglou"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/megis7/risky#readme>

ghc-options: -fplugin=GHC.TypeLits.Extra.Solver -fplugin=GHC.TypeLits.KnownNat.Solver -fplugin=GHC.TypeLits.Normalise

default-extensions:
- ScopedTypeVariables 
- NoImplicitPrelude 
- TypeOperators 
- DataKinds 
- FlexibleContexts 
- TypeApplications 
- BinaryLiterals 
- GADTs
- KindSignatures
- TypeFamilies

dependencies:
- base >= 4.7 && < 5
- deepseq
- clash-lib
- clash-ghc
- clash-prelude
- singletons
- ghc-typelits-natnormalise
- ghc-typelits-knownnat
- ghc-typelits-extra
- HUnit >= 1.6.0.0
- mockery >= 0.3
- QuickCheck
- hspec == 2.*

library:
  source-dirs: 
  - src
  exposed-modules:
  - Core.Definitions
  - Core.RegFile
  - Core.Fetch
  - Core.Decode
  - Core.Execute
  - Core.Writeback

# executable:
#   main: System.hs
#   source-dirs: src
#   dependencies:
#   - base >= 4.7 && < 5
#   - deepseq
#   - clash-lib
#   - clash-ghc
#   - clash-prelude
#   - hspec
#   - singletons
#   - ghc-typelits-natnormalise
#   - ghc-typelits-knownnat
#   - ghc-typelits-extra
#   build-tools: clash-ghc

# tests:
#   spec:
#     main: test/Spec.hs
#     source-dirs:
#       - test
#     dependencies:
#       - hspec == 2.*
#       - QuickCheck
#       - temporary
#       - mockery >= 0.3
#       - interpolate
#       - template-haskell
#       - HUnit >= 1.6.0.0
#     build-tools: hspec-discover